### ISSUE TITLE
Understanding SVG paths

### ISSUE THREAD

**Issue by rfrenoy** [Mehdi-H/WeeklyCuration#1]
Not related to data/ML at all, but I loved [this interactive tutorial](https://www.nan.fyi/svg-paths) about SVG paths. It explains how SVG are described and show sandboxes where people can experiment. Very pedagogical, I also like very much how this blog is structured (the inline comments 🤩). I think it is inspiring and worth visiting.

**Comment by Mehdi-H** [comment]
Wahou, thanks @rfrenoy ! 

I love the animations (and the domain name ^^)

I'll add it to next issue, for 17th of July !

**Comment by Mehdi-H** [comment]
ℹ️ I opened this pull request #2 if you want to see a preview

The branch will be merged between now and next Monday

(Content of NEXT_WEEK.md will move into the README.md, NEXT_WEEK.md will then be purged)

**Comment by Mehdi-H** [comment]
Merged, and released here : https://github.com/Mehdi-H/WeeklyCuration/releases/tag/issue%232 !
